# Generated by Django 2.1.1 on 2018-09-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Knowte',
        ),
    ]
